#!/bin/bash
IMAGE_NAME=lighttpd-server
docker run --rm -it --privileged \
    -v $(pwd)/www/lab:/var/www/html/lab \
    -v $(pwd)/www/lighttpd.conf:/etc/lighttpd/lighttpd.conf \
    -v $(pwd)/www/php.ini:/usr/local/etc/php/php.ini \
    -v $(pwd)/www/root_profile:/etc/profile \
    ${IMAGE_NAME} \
    "$@"